# Generated by Django 5.2.1 on 2025-05-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='task_files',
        ),
        migrations.AddField(
            model_name='assignment',
            name='solution_file',
            field=models.CharField(default='sol1.txt', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='task_file',
            field=models.CharField(default='tasks.pdf', max_length=1024),
            preserve_default=False,
        ),
    ]
