# Generated by Django 5.2.1 on 2025-05-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_remove_assignment_task_files_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='classroom',
            new_name='class_id',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='solution_file',
            field=models.FileField(max_length=1024, upload_to=''),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='task_file',
            field=models.FileField(max_length=1024, upload_to=''),
        ),
    ]
