# Generated by Django 5.2.1 on 2025-05-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_rename_classroom_assignment_class_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='class_id',
            new_name='classroom',
        ),
    ]
