# Generated by Django 5.2.1 on 2025-05-22 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_rename_class_id_assignment_classroom'),
        ('classes', '0003_alter_class_invite_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('classroom', 'name')},
        ),
    ]
