# Generated by Django 5.2.1 on 2025-06-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_assignment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_hand_written',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
