# Generated by Django 5.2.1 on 2025-06-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_submission_is_hand_written'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submitted_files',
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(default=None, max_length=1024, upload_to=''),
            preserve_default=False,
        ),
    ]
