# Generated by Django 5.2.1 on 2025-06-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_remove_submission_submitted_files_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submitted_file',
            new_name='submitted_files',
        ),
    ]
