# Generated by Django 5.2.1 on 2025-06-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_rename_submitted_file_submission_submitted_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submitted_files',
            new_name='submitted_file',
        ),
    ]
