# Generated by Django 5.2.1 on 2025-06-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_rename_submitted_files_submission_submitted_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
