# Generated by Django 5.2.1 on 2025-05-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('subject', 'section')},
        ),
    ]
